modulespath: 'build\bin'
hosts:
  - domain: localhost
    listen:
      port: 3000
      routes:
        - name: \/proxy
          modules:
            - name: proxy
              configs:
                hostname: '127.0.0.1'
                port: 8080
        - name: \/documentation
          modules:
            - name: file
              configs:
                root: .
        - name: \/.*\.php$
          modules:
            - name: php
              configs:
                root: example\www
        - name: \/
          modules:
            - name: file
              configs:
                root: example\www
