modulespath: 'build/lib'
hosts:
  - domain: localhost
    listen:
      port: 8080
      routes:
        - name: \/.*\.php$
          modules:
            - name: php
              configs:
                root: example/www
        - name: \/
          modules:
            - name: file
              configs:
                root: example/www
