modulespath: 'build/lib'
hosts:
  - domain: localhost
    listen:
      port: 8080
      routes:
        - name: \/proxy
          modules:
            - name: proxy
              configs:
                hostname: '127.0.0.1'
                port: 80
        - name: \/documentation
          modules:
            - name: file
              configs:
                root: .
        - name: \/.*\.php$
          modules:
            - name: php
              configs:
                root: example/www
        - name: \/
          modules:
            - name: file
              configs:
                root: example/www
